<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>WebAuthn_Client_.NET</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
	<RuntimeIdentifier>linux-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Program.cs" />
    <Compile Remove="WebAuthn.Client.NativeHost\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Formats.Cbor" Version="9.0.8" />
  </ItemGroup>

</Project>
